### ISSUE TITLE
Zürich Volunteers!

### ISSUE THREAD

**Issue by Hoverbear** [RustFestEU/blog.rustfest.eu#12]
Please add a comment here if you're a Swiss local and would like to volunteer to help out!

While we do not have a formal volunteer system we also don't have many formal volunteer tasks. Instead, we ask you to help introduce our attendees to the city and help them have the best experience possible.

If you'd like to volunteer and the ticket price is a barrier to you please get in touch with us at team@rustfest.eu.

**Comment by dthul** [comment]
I plan to attend Rustfest and live in Zürich. So yeah, if there is something I can help with don't hesitate to contact me!

**Comment by bling5630** [comment]
hello ,
I plan to attend Rustfest as a volunteer, my friend also be there and I would like to help you, please let me know what should be the next step,
many thanks,
Tamas

**Comment by skade** [comment]
Hi Tamas,

we're not "guys" and don't want to be addressed as such.

http://zurich.rustfest.eu/about/

Best,
Florian

**Comment by bling5630** [comment]
Hi Florian,

sorry for my mistake, I am not a native English speaker and I will avoid this expression in the future, I didn't like to use the word exclusionary, apologize for it,

I hope I can help you and prove my enthusiasm

Best,

Tamas

**Comment by dns2utf8** [comment]
Thank you all!
