### ISSUE TITLE
Zürich Impl Days

### ISSUE THREAD

**Issue by Hoverbear** [RustFestEU/blog.rustfest.eu#29]
Please leave your name below if you're interested in joining us for Impl Days.

Signing up is not required, we're just using this to gauge interest.

Impl days are on Monday and Tuesday, October 2nd and 3rd: http://blog.rustfest.eu/this-week-in-rustfest-9-impl-days

**Comment by SimonSapin** [comment]
Yes<s>, probably</s>.

**Comment by Hoverbear** [comment]
I will be coming! :)

**Comment by killercup** [comment]
I'll be there!

**Comment by Geal** [comment]
will be there!

**Comment by dns2utf8** [comment]
I will be there!

**Comment by thejpster** [comment]
I'm on the 1620 back to Luton on Sunday, so yes, until about lunchtime.

**Comment by SimonSapin** [comment]
Impl days are on Monday and Tuesday, October 2nd and 3rd: http://blog.rustfest.eu/this-week-in-rustfest-9-impl-days

**Comment by thejpster** [comment]
Oh, my bad. I guess that's a no then!

**Comment by durka** [comment]
Count me in!

**Comment by oli-obk** [comment]
I'll be there.

**Comment by Hoverbear** [comment]
@thejpster I'm going to delete your comments so we can have an accurate count in "participants" on the side. Please don't take offense! :)

**Comment by GuillaumeGomez** [comment]
I'll be there.

**Comment by joshtriplett** [comment]
I'll be there.

**Comment by jamesmunns** [comment]
I'll be there on Monday

**Comment by vakaras** [comment]
I'll be there.

**Comment by faern** [comment]
I'll be there!

**Comment by fpoli** [comment]
I'll be there

**Comment by alexcrichton** [comment]
I'll be there!

**Comment by japaric** [comment]
I'll be there

**Comment by samdolt** [comment]
I'll be there

**Comment by skade** [comment]
I'll be there.

**Comment by exul** [comment]
I'll be there.

**Comment by Nemo157** [comment]
I'll be there

**Comment by gralpli** [comment]
I'll be there on monday.

**Comment by djc** [comment]
I'll be there on Monday.

**Comment by gandro** [comment]
I'll be there.

**Comment by flaki** [comment]
Me too, me too! 🎉

**Comment by pizzaiter** [comment]
I'll be there!

**Comment by utaal** [comment]
I'll be there at least on Monday.

**Comment by bluss** [comment]
I'll be there on monday

**Comment by ogham** [comment]
One more for Monday!

**Comment by gandro** [comment]
Hi folks, just fyi: The venue is

> Quartierhaus Kreis 5
> Sihlquai 115
> 8005 Zürich 

Feel free to drop by any time after 9:00!

**Comment by Hoverbear** [comment]
Thanks so much for all the fun everyone! :)
